apiVersion: v1
kind: Service
metadata:
  labels:
    service: tech-search-backend
  name: tech-search-backend
  namespace: {{ .Values.namespace.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.backend }}
spec:
  ports:
  - name: tech-search-backend-port
    port: {{ .Values.port.backend }}
    targetPort: {{ .Values.port.backend }}
    nodePort: {{ .Values.nodePort.backend }}
  selector:
    service: tech-search-backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tech-search-backend
  name: tech-search-backend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tech-search-backend
  template:
    metadata:
      labels:
        service: tech-search-backend
    spec:
      containers:
      - image: frkoichi/tech-search-backend:latest
        name: tech-search-backend
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: tech-search-config
      restartPolicy: Always