apiVersion: batch/v1
kind: CronJob
metadata:
  name: tech-search-batch
  labels:
    app: {{ .Value.service.name }}
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: {{ .Value.service.name }}
    spec:
      completions: 1
      parallelism: 1
      activeDeadlineSeconds: 3600
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: {{ .Value.service.name }}
        spec:
          restartPolicy: Never
          containers:
            - name: tech-search-batch
              image: frkoichi/tech-search-batch:latest
              imagePullPolicy: Never
              envFrom:
                - configMapRef:
                    name: tech-search-config