apiVersion: batch/v1
kind: CronJob
metadata:
  name: tech-search-batch
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.service.name }}
    tags.datadoghq.com/env: {{ .Values.env }}
    tags.datadoghq.com/service: {{ .Values.service.name }}
    tags.datadoghq.com/version: {{ .Values.service.version }}
spec:
  schedule: "@hourly"
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      completions: 1
      parallelism: 1
      activeDeadlineSeconds: 3600
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: {{ .Values.service.name }}
            tags.datadoghq.com/env: {{ .Values.env }}
            tags.datadoghq.com/service: "tech-search"
            tags.datadoghq.com/version: "1.0"
        spec:
          restartPolicy: Never
          containers:
            - name: tech-search-batch
              image: frkoichi/tech-search-batch:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: tech-search-config-batch
              env:
              - name: DD_ENV
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/env']
              - name: DD_SERVICE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/service']
              - name: DD_VERSION
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['tags.datadoghq.com/version']
              - name: DD_LOGS_INJECTION
                value: "true"
              - name: DD_AGENT_HOST
                valueFrom:
                  fieldRef:
                    fieldPath: status.hostIP