apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-search-config
  namespace: {{ .Values.namespace.name }}
data:
  MERCARI_ENDPOINT: "https://engineering.mercari.com/blog/"
  MERCARI_BASEURL: "https://engineering.mercari.com"
  ZOZO_ENDPOINT: "https://techblog.zozo.com"
  DeNA_ENDPOINT: "https://engineering.dena.com/blog/"
  DeNA_BASEURL: "https://engineering.dena.com"
  CLASSMETHOD_ENDPOINT: "https://dev.classmethod.jp"
  REDIS_TTL: "120"
  REDIS_ENDPOINT: "redis.sandbox.us-east-2.tech-search:6379"
  SEARCH_ENDPOINT_V1: "/techsearch/v1/blogs"
  BACKENDPORT: "80"
  REACT_APP_SEARCH_ENDPOINT: "https://teck-search-backend.staging.udacity.impara8.com/techsearch/v1/blogs"
  REACT_APP_BACKETENDPOINT: "https://tech-search.s3.ap-northeast-1.amazonaws.com/"
  REACT_APP_IMEXTENSION: ".png"