apiVersion: v1
kind: Service
metadata:
  labels:
    service: tech-search-frontend
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.frontend }}

    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.acm.arn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: https
    port: 443
    targetPort: {{ .Values.port.frontend }}
  selector:
    service: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tech-search-frontend
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: frkoichi/tech-search-frontend:latest
        name: tech-search-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.port.frontend }}
        envFrom:
        - configMapRef:
            name: tech-search-config-frontend
      restartPolicy: Always