apiVersion: v1
kind: Service
metadata:
  labels:
    service: tech-search-frontend
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.frontend }}
spec:
  ports:
  - name: tech-search-frontend-port
    port: {{ .Values.port.frontend }}
    targetPort: {{ .Values.port.frontend }}
    nodePort: {{ .Values.nodePort.frontend }}
  selector:
    service: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: tech-search-frontend
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: frkoichi/tech-search-frontend:latest
        name: tech-search-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: tech-search-config
      restartPolicy: Always