apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Values.service.name }}
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns.frontend }}
spec:
  ports:
  - name: tech-search-frontend-port
    port: 80
    targetPort: {{ .Values.port.frontend }}
    nodePort: {{ .Values.nodePort.frontend }}
  selector:
    service: {{ .Values.service.name }}
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.service.name }}
  name: tech-search-frontend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.service.name }}
    spec:
      containers:
      - image: frkoichi/tech-search-frontend:latest
        name: tech-search-frontend
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: tech-search-config
      restartPolicy: Always