apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tech-search-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: infrastructure/helm
    repoURL: https://github.com/takahiro-impara/tech_search
    targetRevision: HEAD